### ISSUE TITLE
Describe current process of a drive

### ISSUE THREAD

**Issue by adamgajzlerowicz** [CodeForPoznan/pah-fm#159]
Can we please get a description of current process from entering a vehicle, through obtaining all the details to approval of the drive. Ideally in a form of bullet points.

**Comment by OlaPAH** [comment]
Hey Guys,
For paper logbook steps are followin:
1. driver and passenger enter the car. Driver fills in 3 fields:
Date | Start Location | Start KM | Passenger name
in the company of the passenger.
2. Passenger gives driver destination and purpose of the visit, which driver also fills in.
3. During the trip the final destination and puropse of the trip might change due to the context.
4. At the end of the trip driver fills in fields: 
End KM  | Total KM | Fuel LTR     
5. Passenger fills in the project number and signs the logbook.

We were thinking that maybe there shall be 2 submissions from the driver - with initial data and end data? And both would have to be done in the presence of passenger.

**Comment by adamgajzlerowicz** [comment]
Thank you for this. Am I right to say that at step 1 and step 4 passenger also checks the car KM meter?

**Comment by OlaPAH** [comment]
Actually yes - driver is filling it in and passenger shall be next to him to accept the data and place the signature in the step 5. So I was thinking - how about driver making 2 submissions? And he would be obliged to make them in the presence of the passenger. Just like he is supposed to be doing that now. Then passenger would be accepting the data from one e-mailo only, but this e-mail could contain data from both submissions.
I have some other notes already but I want to discuss it with Sergiey and today he had no possibility to check the app out.
And one question I have is - app will be downloaded, right? 

Plus a request in the end - if you see me not replying here, could you please contact me on Gitter as well? I mean in this conditions I have very limited access to my e-mails and I am checking gitter once I have internet connection in my laptop. And it's more obvious someone needs something from me when it is shown there.

**Comment by OlaPAH** [comment]
After my first few tries I have following observations:
1.	Car shall be assigned to driver as we hire drivers with their own cars;
2.	Each car shall have the average fuel consumption assigned to it so the total fuel consumption per ride could be calculated;
3.	After ride details are submitted, app shall redirect us to “Home” page instead of showing a new empty form because a person can have a feeling that data was not submitted;
4.	In confirmation e-mail the text of the message is cut: “The starting mileage was 15890, the en Please confirm your participation and select your project by clicking on the link below.”;
5.	E-mail does not contain trip description and it should;
6.	I was thinking that actually the driver could make two submission, first with Starting mileage and second with ending mileage. All other information from the form would be filled in in the first submission. Second submission could contain the ending mileage and number of the project. Procedure would state that both submissions shall be done in the presence of passenger. Then the passenger would receive all data in one e-mail to confirm and add comments if needed.

Also - when I am opening the website on the phone - it is not displayed properly. I have screenshots - how can I attach them?

**Comment by juliaanholcer** [comment]
ad. 3 We decide to display a list of previous rides instead of a home page, so after sending the form there will be a redirection to this list view. Additionally, we are considering some kind of notification service to give a user an update, whether the form was submitted correctly and the data were stored in the database.

If you want to attach files just drag and drop them or paste (after previously copying to clipboard) to the comment textarea.
