### ISSUE TITLE
[SECURITY] server accept drives after logout

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#167]
## Current Behavior:
User can add new drives after logout with using previous token.

## Expected Behavior:
Logout user shouldn't have possible to add new drive. His token should be invalidated.

**Comment by arturtamborski** [comment]
I'm fairly certain that the bug is in this line https://github.com/CodeForPoznan/pah-fm/blob/6b77d678419cc59d59de332b0bee35ca40f20cbb/backend/fleet_management/models.py#L87
I'll check this later and see how this can be fixed.

**Comment by arturtamborski** [comment]
We're not really logging anyone anywhere (in classical sense), our authentication model relies on JWT token which currently is not time based, which means that any login is permanent until next one occurs (which would replace token).

One solution that comes to mind is to replace JWT with its time-based version and set up some constant timeout, like, say 30 minutes.

**Comment by arturtamborski** [comment]
But when I think about it - this solution might introduce cumbersome login from users' perspective. Here's an example:
- user logs in, receives 30min token
- gets on the road and looses internet connection (can't update his token in time)
- arrives to destination, gets his internet access back but his verification token is already invalid so he can't submit a drive with current session

At this point his session is invalid and so the app can go in two ways:
- web page redirects him back to login page where he inputs credentials
- user navigates back to drives form, fills out details (some of which are saved?)
- finally submits a drive

or... 
- web page accepts the submission but does not send immediately
- instead a notification of some kind (popup?) appears which instructs the user to re log in in order to finalize the drive submission
- user logs in again, gets new token, app synces drives in background

Both solutions feel seem annoying for someone who submits few drives a day in few hours gap.

Which, in turn suggests that maybe it would be good enough if the token was walid for 24 hours instead? This kinda hits both birds with one stone.

What do you think?

**Comment by magul** [comment]
I haven't yet read RfC that defines JWT but as in `codeforpoznan.pl_v3` we should have an access token and refresh token and store somewhere refresh tokens that would be still valid, but were revoked (`codeforpoznan.pl_v3` stores that in dedicated DB table AFAIR).

**Comment by arturtamborski** [comment]
Coming back to this, we do actually use time-based JWT tokens.
It just so happens that these tokens are valid for _30 days_, (configured in `settings.py`).
What's even more interesting is that this was increased intentionally to 30 days via #108 which was done on behalf of #95. 

So again, we can decrease the limit to something like a day or so, but I'm worried that this would cause some trouble for our users.

Better solution would be to set the expiration date somewhat low, like a 6 hours, _but_ also enable refresh tokens which would give the app some time to ping us back and ask for extending the session via refresh token.

The effect would be that user stays logged in as long as the refresh token has is not expired - or in case it did - user had internet connection so that the app can pull new token.

Any thoughts on this solution? @magul, @monikakrawczak?

All of this is described here: https://jpadilla.github.io/django-rest-framework-jwt/

**Comment by OtisRed** [comment]
Not relevant anymore (kinda overdue :P)
