### ISSUE TITLE
My car

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#235]
Add solution for simplifying car selection.
User shoudn't has to choose the same car over and over.

**Comment by monikakrawczak** [comment]
Propose last chosen car

**Comment by arturtamborski** [comment]
Maybe we could use [vue-multiselect](https://vue-multiselect.js.org/) for this?

**Comment by adamgajzlerowicz** [comment]
How about storing last chosen car id in session storage?

**Comment by arturtamborski** [comment]
This should be easy enough to do by basing off work on similar feature implemented here https://github.com/CodeForPoznan/pah-fm/pull/348

**Comment by arturtamborski** [comment]
Relates to #383

**Comment by arturtamborski** [comment]
This one's finished, according to the AC in first post. It's still good idea to introduce vue-multiselect for easier use but that's a story for another ticket.

**Comment by pniedzwiedzinski** [comment]
In which PR it was fixed?

**Comment by arturtamborski** [comment]
I believe it was done in https://github.com/CodeForPoznan/pah-fm/pull/361.

I closed it because the description states that:
> User shoudn't has to choose the same car over and over.

implies that this issue should be resolved by remembering the selected car, which is implemented and works. It would be nice to use vue-multiselect as we did for Passenger selector, but that wasn't specified in first post, so it wasn't an requirement.
