### ISSUE TITLE
Cheapest device to be advised

### ISSUE THREAD

**Issue by monikakrawczak** [CodeForPoznan/pah-fm#259]

**Comment by arturtamborski** [comment]
Basically any smartphone released after 2010 will be OK.

Technically speaking, `pah-fm` needs reasonably stable platform with browser, bit of ram and some place for local storage. This is assured with practically any smartphone. The most important feature would be `localStorage` which is implemented basically since the start of modern [browsers](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage#Browser_compatibility). We are not doing anything compute-heavy on client side either so that's not a big concern.
Application also needs network but that's more dependent on telecom infrastructure of given country. 

I can safely assume that _any working_ smartphone will be fine, therefore it's unnecessary to advise any specific device, but if I had to I'd take something cheap from retail/resellers market as they tend to be rather good quality for the money and they come with at least some degree of certainty that someone checked it and confirmed that it works correctly.
