### ISSUE TITLE
'Sync' button

### ISSUE THREAD

**Issue by pniedzwiedzinski** [CodeForPoznan/pah-fm#422]
I think it would be nice to add a 'Sync now' button - it's nice to be sure that it's synced

This button would dispatch the 'SYNC' action

**Comment by OtisRed** [comment]
In which view exactly "syncing" should take place?

**Comment by arturtamborski** [comment]
DrivesView.vue. SYNC action is defined in `src/store/actions.js:73`

**Comment by OtisRed** [comment]
I meant where the button is supposed to be? :P

**Comment by OtisRed** [comment]
I started working on it - I assumed it should be somewhere in the driver's view, preferably around the header or status components so that the button is rendered both in a ride form and the rides list. At the same time I started to re-arrange the grid using bootstrap because right now it all holds on absolute values, which can make a mess, if you consider any other view than mobile.

**Comment by OtisRed** [comment]
I remember we decided to skip this
