### ISSUE TITLE
Passenger input type

### ISSUE THREAD

**Issue by pniedzwiedzinski** [CodeForPoznan/pah-fm#425]
In passenger view input has type `text` but it should be `number` so the numeric keyboard would pop up on mobile.

**Comment by arturtamborski** [comment]
There's a problem with that - if I remember correctly, the `number` type is not a good fit for it, because the code drive checksum can start with zeros which will be omitted by the `number` type resulting in shorter value that does not match the typed in number, and there's no way of dealing with that other than using a `text` type. We still can force numeric keyboard by using attributes: `numeric` and `pattern`, similarly to signature input box in DriveFormView.

**Comment by pniedzwiedzinski** [comment]
Yep, I think that this works the best: https://codepen.io/pniedzwiedzinski/pen/vYOEpzJ

**Comment by arturtamborski** [comment]
That's certainly a better option, though if you don't mind I have few suggestions:
- "Please match requested format" is ambiguous without further instructions, consider adding `title="Please type in 6 digits"`: https://webdesign.tutsplus.com/tutorials/html5-form-validation-with-the-pattern-attribute--cms-25145
- `type="tel"` brings the numeric keyboard the most reliably I think 
- `minlength="6" / maxlength="6"`  can be ignored if pattern with `{6}` is used (?)
- `maxlenght` -> `maxlength` ;)

**Comment by pniedzwiedzinski** [comment]
`pattern` and `maxlength` work differently, the pattern checks the content after pressing the submit button, and `maxlength` prevents from typing longer than 6 characters
