### ISSUE TITLE
Newly submitted drive does not show up under Drives list until next login

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#515]
reproducible on dev.pahfm.codeforpoznan.pl. Try adding a drive (can be unverified), go to drives/, notice that it's not there. Refresh does not always help, though logout-login always works.

**Comment by juliaanholcer** [comment]
It doesn't look as a frontend issue to me - the list of drives that are fetched from backend after the drive was added, simply doesn't contain added drive(s) and won't be displayed as long as the user log out and log in again. I don't see any significant difference between the two requests that return correct and wrong data. There is an 'age' response headers present for the wrong request so maybe this issue is somehow related to cache.

**Comment by arturtamborski** [comment]
Thanks for investigating that. It's great to hear that the issue does not come from frontend code, because that means that production is free of this bug (because of how it's set up currently).

Therefore I can certainly claim that this problem can be observed and reproduced _only_ on our dev environment.

The `age` header is a really valuable insight! That could mean that CloudFront headers are not quite the way they should be.
You won't be able to replicate the issue easily without access to AWS so I'll happily take over the ticket and investigate it further :)

**Comment by arturtamborski** [comment]
aaand I have some results. Turns out that our infra configuration cached GET and HEAD by default with quite a bit of TTL.
The same problem was discovered when I worked on dev.codeforpoznan.pl.

Anyway, the fix is here https://github.com/CodeForPoznan/Infrastructure/pull/75 and it's _in place_, so you can check it for yourself and confirm that it is in fact working.

**Comment by arturtamborski** [comment]
Fixed here: https://github.com/CodeForPoznan/Infrastructure/pull/75 closing.
