### ISSUE TITLE
Fix error markings on vue-select fields

### ISSUE THREAD

**Issue by arturtamborski** [CodeForPoznan/pah-fm#536]
They look ugly and don't indicate error at all.
![image](https://user-images.githubusercontent.com/8676740/88091177-fe45c000-cb8e-11ea-943b-4d7563ee3d00.png)

**Comment by OtisRed** [comment]
@juliaanholcer (or whoever is going to take it) I won't deliver it today so I will leave it to you. However here's what I've found:

I located the problem to the [driver's form](https://github.com/CodeForPoznan/pah-fm/blob/master/frontend/src/views/DriveFormView.vue) when you add a new route (it wasn't in a description so I hope it will save you few seconds of figuring out where this image comes from :P ). 

The problem appears when you fill the form by keyboard. When you "tab" to the next field, starting  from the first dropdown select, it triggers premature validation, which puts a red "X" over all the fields that are invalid. In case of the folllowing dropdowns then, this red X (that signals the field is invalid) overlays two normal select icons, which are there, anyway: the gray downward dash (signifiying dropdown) and  the gray "X", which resets value for the given field.

Steps to reproduce:
1) Log in as a driver
2) Tap on first select input 
3) "Tab" to the next field
4) At this point validation should be triggered causing a trouble

I may be wrong, but I think that this "form-control select" class, which seems to be behind it, is imported from [here](https://vue-select.org/guide/validation.html#required). 

When I think of the solution one way would be to stop validation triggered by keyboard, or render the icons in some visually sensible manner so that they don't overlay each other. If you figure out the solution, please ping me, so I can learn how you've solved it, because I don't know how to do it myself :)

Hope this will help you get the job done :)

**Comment by juliaanholcer** [comment]
> They look ugly and don't indicate an error at all.

There are two things: 
1. Styles for form fields error state come from bootstrap and this is the origin of the red 'x' sign.
2. Validation of the form is triggered only on submit action so even if you enter a valid value after the field has been validated previously as invalid, its validity state won't change as long as you click the submit button again. This is of course not the best user experience but it was made this way at the beginning and maybe we should change how and when validation is triggered for all forms. However, this is probably not the scope of this task.

I've decided that select fields will get a different 'invalid' class than regular form fields and when there is an error, they will have a red border but without 'x' icon. At least for now :-)
