### ISSUE TITLE
App doesn't work on Safari

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/pah-fm#537]
- page loads ok (200 on localhost, app.js and chuck-vendors.js)
- one error in console `TypeError: undefined is not an object (evaluating 'user.groups.map')`

**Comment by w1stler** [comment]
I can do some investigation here with some guidance. ;-)

**Comment by arturtamborski** [comment]
```diff
diff --git a/frontend/src/mixins/GroupGuardMixin.js b/frontend/src/mixins/GroupGuardMixin.js
index 3e13013..044724a 100644
--- a/frontend/src/mixins/GroupGuardMixin.js
+++ b/frontend/src/mixins/GroupGuardMixin.js
@@ -3,7 +3,7 @@ import { groupBasedRoutes } from '../router/routes';
 import { reverseObject } from '../services/reverseObject';
 
 const { user } = store.state;
-const groups = user ? user.groups.map(({ name }) => name.toLowerCase()) : [];
+const groups = user && user.groups ? user.groups.map(({ name }) => name.toLowerCase()) : [];
 
 const getRouteGroup = (routeName) => {
   const groupBasedRouteNames = Object.keys(groupBasedRoutes).reduce(

```

this should be enough to fix that bug, I suspect its because you're logging as admin user (hello@codeforpoznan.pl) who does not have any group assigned by default hence the `map` fails. Though this is not strictly related with Safari it might fix the problem.

You can try to log in as admin (hello@) after assinging some group to him in admin panel. I suspect the page will load just fine then.

**Comment by arturtamborski** [comment]
Related issue #413

**Comment by juliaanholcer** [comment]
The problem was that the available routes to a user are based on his group, and for a user without a group, it is an empty list. After a successful login user is redirected to the default `/drive` route, which is unavailable for admin, the application tries to redirect the user to the first from the list of available ones. Since there is no first one - an error occurs.

<img width="729" alt="Screenshot 2020-08-19 at 20 04 16" src="https://user-images.githubusercontent.com/28116755/90675403-b338ce80-e25a-11ea-9b4a-9d525634292a.png">

By the way, I noticed that for users who are not from the Drivers group, we should not fetch data like passengers, cars, etc., or synchronize drives, so I fixed it by the way.
